### ISSUE TITLE
node.path

### ISSUE THREAD

**Issue by alex-shamshurin** [klauskpm/gulp-path#1]
I see this extension does not see https://nodejs.org/api/path.html for resolving relative paths, combining paths with platform specific delimiters via path.join(). So is it a platform independent?

**Comment by klauskpm** [comment]
Yes. It does not rely on Node.js path. It's completelly independent, at the given moment.

**Comment by klauskpm** [comment]
If you are talking about it been independent from Node.js, yes. It's independent :+1:

**Comment by alex-shamshurin** [comment]
No, I meant a platform independency.

**Comment by klauskpm** [comment]
Oh! Paths working for Linux, Windows, etc; Didn't know path.join() also do it.
I think the code is not, but, didn't had any problem with Linux or Windows on my machines.
It will be in the next update, to prevent this type of error.
Thank you :)

**Comment by alex-shamshurin** [comment]
Right now I do not remember my issue and I why asked this question, but I had some problems with resolving paths. I think more preferable is using Node.path inside this package.

**Comment by klauskpm** [comment]
Updated. From v3.0.3 forward will be using `path.join()`. Thank you.
