### ISSUE TITLE
filesPath is not a function.

### ISSUE THREAD

**Issue by licdream** [klauskpm/gulp-path#2]
Hey,there. There is a problem confuses me. When I set my paths like this:

``` javascript
var gulpPath = require("gulp-path");`
```

``` javascript
var root = new gulpPath.Base();
```

``` javascript
var path = {
    mainLess: root.filesPath("./css/", "main", "css")
}; 
```

And the document says in this kind of option, gulp-path will return a very same object like that:

``` javascript
 {
    basePaths: {
        src: './source/path',
        dest: './destination/path'
    },
    // Path class will be explained in the following 
    Path: function ([paths , extensions]) {},
    // filesPath method will be explained in the following 
    filesPath: function([paths, files, extensions])
} 
```

But the console always says the `root.filesPath` is not a function.It makes me puzzled. 
I'm not sure if this is an issue with `gulp-path`.

**Comment by klauskpm** [comment]
Thanks for your feedback. I just updated the documentation.

It didn't make sense to have a `filesPath` there and I removed it before, but didn't updated the documentation.

I'd recommend you to use like this:

``` js
var gulpPath = require("gulp-path");
var path = {
    mainLess: gulpPath.filesPath("./css/", "main", "css")
}; 
```
