### ISSUE TITLE
Different last `src` and `dest` folder names

### ISSUE THREAD

**Issue by ghost** [klauskpm/gulp-path#3]
Thank you for this wonderful package. 

What if my **last in path** `src` and `dest` folder names are different?
In the following example, in the `src` and `dest` paths the last output folder names are same - `js`:

```
// js.src           = [ './assets/js/**/*.js' ] 
// js.dest          = [ './resources/js/' ] 
js: assets.Path('js', 'js'),
```

But what I if need:

```
// styles.src           = [ './development/sass/**/*+.(sass|scss)' ] 
// styles.dest          = [ './production/css/' ] 
```
The `Base` will not work here: if to setup 

```
const STYLES= new gulpPath.Base({
    src: [
        './development/public/sass',
        './development/admin/sass'
    ],
    dest: [
        './production/public/css',
        './production/admin/css',
    ]
});
```

for task

```
gulp.task('sass', function(){
    return gulp.src(STYLES)
            .pipe(sass());
});

```

, it will cause the error:

`Error: Invalid glob argument: [object Object]`

Also, the declaration:
`const test = STYLES.files(null, 'sass');`

will cause:

`TypeError: STYLES.files is not a function`

**Comment by klauskpm** [comment]
Glad to hear you liked it and sorry about my documentation. It needs better examples.

Looking at your code, I would do this:
```JavaScript
gulp.task('sass', function(){
    //return gulp.src(STYLES)
    return gulp.src(STYLES.src)
            .pipe(sass());
});
```

When you do new, it returns the `src` and `dest` properties, and also the `Path` method. The `src` method is waiting for a blob, so you could pass any one of those properties stored in STYLES.

Also, when you try to find a file in here `const test = STYLES.files(null, 'sass');` you are using a method that doesn't, but will, after using generating a path, with the `Path` method. This code is old, and after your comment I've finally saw the mistake I made and will create a new version of this plugin, but, until them to make your code work, do this:
```JavaScript
const cssPath = STYLES.Path();
const test = cssPath.files(null, 'sass');
```

It's not the best solution, but the one that exists right now.
I'll be working in a new version with a better solution.

**Comment by ghost** [comment]
Thank you for the answer!

Do you mean that `STYLES.src` in your first listing is same `STYLES` that I declared in my question as `gulpPath.Base`? If so, it does not work, because first we need to invoke the `basePaths`:
```

console.log(CSS_DEVELOPMENT_CHANNELS.src); // undefined
console.log(CSS_DEVELOPMENT_CHANNELS.dest); // undefined
console.log(CSS_DEVELOPMENT_CHANNELS.basePaths); //  { dest: [ './production/public/css', './production/admin/css' ],  src: [ './development/public/sass', './development/admin/sass' ] }
console.log(CSS_DEVELOPMENT_CHANNELS.basePaths.src); // [ './development/public/sass', './development/admin/sass' ] 
console.log(CSS_DEVELOPMENT_CHANNELS.basePaths.dest); // [ './production/public/css', './production/admin/css' ]
```
Now it's required to convert somehow the `STYLES` from my listing to `.Path()`, because the `Base()` could not be used as `gulp.scs()` argument. I told "to convert" because we don't need to define any child directories inside `STYLES.Path`.

**Comment by klauskpm** [comment]
You are right! It returns a basePath with src and dest. Sorry about that.

My code really wasn't prepared for a case like yours, and the fault to it was my lack of vision, but I think that will work.
```JavaScript
const STYLES= new gulpPath.Base({
    src: [
        './development/public/sass',
        './development/admin/sass'
    ],
    dest: [
        './production/public/css',
        './production/admin/css',
    ]
});
const paths = {
    sass: STYLES.Path().files(null, 'sass')
};

gulp.task('sass', function(){
    return gulp.src(paths.sass.src)
            .pipe(sass());
});
```

I've finished v4.0.0, with your case in mind, and it is available on dev (not through npm).
I hope to finish the docs until today's end to publish it.

Edit: v4.0.0 is online with the new docs

**Comment by ghost** [comment]
Good work! Thank you for your efforts.
You package becomes more powerful and it's has a lot of potential in the future.
Thank you for answer on my issue!

Kind regards
